
package ws.echo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Echo", targetNamespace = "http://echo.ws/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Echo {


    /**
     * 
     * @param count
     * @param message
     */
    @WebMethod(action = "echo")
    @Action(input = "echo", output = "http://echo.ws/Echo/echoResponse")
    public void echo(
        @WebParam(name = "message", mode = WebParam.Mode.INOUT, partName = "message")
        Holder<String> message,
        @WebParam(name = "count", partName = "count")
        int count);

}
