
package ws.echo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EchoImplService", targetNamespace = "http://echo.ws/", wsdlLocation = "http://localhost:8080/ws/echo?wsdl")
public class EchoImplService
    extends Service
{

    private final static URL ECHOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ECHOIMPLSERVICE_EXCEPTION;
    private final static QName ECHOIMPLSERVICE_QNAME = new QName("http://echo.ws/", "EchoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/echo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECHOIMPLSERVICE_WSDL_LOCATION = url;
        ECHOIMPLSERVICE_EXCEPTION = e;
    }

    public EchoImplService() {
        super(__getWsdlLocation(), ECHOIMPLSERVICE_QNAME);
    }

    public EchoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECHOIMPLSERVICE_QNAME, features);
    }

    public EchoImplService(URL wsdlLocation) {
        super(wsdlLocation, ECHOIMPLSERVICE_QNAME);
    }

    public EchoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECHOIMPLSERVICE_QNAME, features);
    }

    public EchoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Echo
     */
    @WebEndpoint(name = "EchoImplPort")
    public Echo getEchoImplPort() {
        return super.getPort(new QName("http://echo.ws/", "EchoImplPort"), Echo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Echo
     */
    @WebEndpoint(name = "EchoImplPort")
    public Echo getEchoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://echo.ws/", "EchoImplPort"), Echo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECHOIMPLSERVICE_EXCEPTION!= null) {
            throw ECHOIMPLSERVICE_EXCEPTION;
        }
        return ECHOIMPLSERVICE_WSDL_LOCATION;
    }

}
